<?xml version="1.0" encoding="UTF-8"?>
<testng-results ignored="0" total="3" passed="1" failed="1" skipped="1">
  <reporter-output>
    <line>
      <![CDATA[Your Tc is started]]>
    </line>
    <line>
      <![CDATA[Sorry your TC is failed]]>
    </line>
    <line>
      <![CDATA[Your Tc is started]]>
    </line>
    <line>
      <![CDATA[TC a is running]]>
    </line>
    <line>
      <![CDATA[Your TC is success]]>
    </line>
    <line>
      <![CDATA[Your Tc is started]]>
    </line>
    <line>
      <![CDATA[Your TC is skipped]]>
    </line>
  </reporter-output>
  <suite started-at="2022-04-04T03:32:29 GMT-07:00" name="Default suite" finished-at="2022-04-04T03:32:29 GMT-07:00" duration-ms="136">
    <groups>
    </groups>
    <test started-at="2022-04-04T03:32:29 GMT-07:00" name="Default test" finished-at="2022-04-04T03:32:29 GMT-07:00" duration-ms="136">
      <class name="listener.Testing">
        <test-method signature="b()[pri:0, instance:listener.Testing@4b45a2f5]" started-at="2022-04-04T03:32:29 GMT-07:00" name="b" finished-at="2022-04-04T03:32:29 GMT-07:00" duration-ms="21" status="FAIL">
          <exception class="java.lang.AssertionError">
            <message>
              <![CDATA[null]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.AssertionError: null
at org.testng.Assert.fail(Assert.java:99)
at org.testng.Assert.fail(Assert.java:106)
at listener.Testing.b(Testing.java:15)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.base/java.lang.reflect.Method.invoke(Method.java:568)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:133)
at org.testng.internal.TestInvoker.invokeMethod(TestInvoker.java:598)
at org.testng.internal.TestInvoker.invokeTestMethod(TestInvoker.java:173)
at org.testng.internal.MethodRunner.runInSequence(MethodRunner.java:46)
at org.testng.internal.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:824)
at org.testng.internal.TestInvoker.invokeTestMethods(TestInvoker.java:146)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:146)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:128)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
at org.testng.TestRunner.privateRun(TestRunner.java:794)
at org.testng.TestRunner.run(TestRunner.java:596)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:377)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:371)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:332)
at org.testng.SuiteRunner.run(SuiteRunner.java:276)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:53)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:96)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1212)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1134)
at org.testng.TestNG.runSuites(TestNG.java:1063)
at org.testng.TestNG.run(TestNG.java:1031)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:115)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.AssertionError -->
          <reporter-output>
            <line>
              <![CDATA[Your Tc is started]]>
            </line>
            <line>
              <![CDATA[Sorry your TC is failed]]>
            </line>
          </reporter-output>
        </test-method> <!-- b -->
        <test-method signature="a()[pri:0, instance:listener.Testing@4b45a2f5]" started-at="2022-04-04T03:32:29 GMT-07:00" name="a" finished-at="2022-04-04T03:32:29 GMT-07:00" duration-ms="4" status="PASS">
          <reporter-output>
            <line>
              <![CDATA[Your Tc is started]]>
            </line>
            <line>
              <![CDATA[TC a is running]]>
            </line>
            <line>
              <![CDATA[Your TC is success]]>
            </line>
          </reporter-output>
        </test-method> <!-- a -->
        <test-method signature="c()[pri:0, instance:listener.Testing@4b45a2f5]" started-at="2022-04-04T03:32:29 GMT-07:00" name="c" finished-at="2022-04-04T03:32:29 GMT-07:00" depends-on-methods="listener.Testing.b" duration-ms="0" status="SKIP">
          <exception class="java.lang.Throwable">
            <message>
              <![CDATA[Method Testing.c()[pri:0, instance:listener.Testing@4b45a2f5] depends on not successfully finished methods]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.Throwable: Method Testing.c()[pri:0, instance:listener.Testing@4b45a2f5] depends on not successfully finished methods
at org.testng.internal.TestInvoker.invokeTestMethods(TestInvoker.java:102)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:146)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:128)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
at org.testng.TestRunner.privateRun(TestRunner.java:794)
at org.testng.TestRunner.run(TestRunner.java:596)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:377)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:371)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:332)
at org.testng.SuiteRunner.run(SuiteRunner.java:276)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:53)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:96)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1212)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1134)
at org.testng.TestNG.runSuites(TestNG.java:1063)
at org.testng.TestNG.run(TestNG.java:1031)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:115)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.Throwable -->
          <reporter-output>
            <line>
              <![CDATA[Your TC is skipped]]>
            </line>
          </reporter-output>
        </test-method> <!-- c -->
      </class> <!-- listener.Testing -->
    </test> <!-- Default test -->
  </suite> <!-- Default suite -->
</testng-results>
